spring.application.name=monolith-dpt

spring.datasource.url=jdbc:postgresql://localhost:55432/dpt
spring.datasource.username=dpt
spring.datasource.password=dpt123

# ===== JPA =====
# Hibernate ch? ki?m tra, không s?a DB
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=false

# ===== FLYWAY =====
# M?i thay ??i schema ch? ???c qua Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

logging.level.org.springframework.security=TRACE

# Expose actuator endpoints
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.prometheus.metrics.export.enabled=true


application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

logging.level.org.springframework.jdbc.core = TRACE


logging.file.name=./log/application.log
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG